# Game settings
WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 920
FPS = 60

# time for physics, DON'T CHANGE
FIXED_DT = 1 / 60

FONT_SIZE = 20

# Positioning
WIDTH_CENTER =  WINDOW_WIDTH / 2
HEIGHT_CENTER = WINDOW_HEIGHT / 2
SCALE = WINDOW_WIDTH / 2 / 8e8